command:
  global:
    override: false
    active: true
  local:
    override: false
    active: true
  temp:
    override: false
    active: true
  unban:
    override: false
    active: true
  checkban:
    override: false
    active: true
saveKick: true
database:
  username: root
  password: password
  driverclass: com.mysql.jdbc.Driver
  jdbcurl: jdbc:mysql://localhost:3306/secureban
remote:
  apikey: xxxx
  serviceurl: http://www.minecraftadmin.de/SecureBan
loglevel: INFO
multiserver: false