command:
    global:
        override: false
        active: true
    local:
        override: false
        active: true
    temp:
        override: false
        active: true
database:
    username: sa
    password:
    driverclass:
    jdbcurl:
remote:
    apikey: xxxx
    serviceurl: http://www.minecraftadmin.de/SecureBan