main: de.minecraftadmin.secureban.SecureBan
name: SecureBan
version: ${project.version}
website: http://minecraftadmin.de
description: Let us ban together the whole world
commands:
  localban:
    usage: /<command> [username] [reason]
    description: ban a player localy
    permission: secureban.localban
    permission-message: You dont have permisson to use this command
  globalban:
    usage: /<command> [username] [reason]
    description: ban a player global
    permission: secureban.globalban
    permission-message: You dont have permisson to use this command
  tempban:
    usage: /<command> [username] [numberM/H/D] [reason]
    description: ban a player temporary
    permission: secureban.tempban
    permission-message: You dont have permisson to use this command
  unban:
    usage: /<command> [username]
    description: unban a player
    permission: secureban.unban
    permission-message: You dont have permisson to use this command
  checkban:
    usage: /<command> [username]
    description: list all bans of a player
    permission: secureban.check
    permission-message: You dont have permisson to use this command
  kick:
    usage: /<command> [username] [reason]
    description: kick the player and save it to the database
    permission: secureban.kick
    permission-message: You dont have permisson to use this command
authors: [BADMAN152,sourcemaker]
database: true