main: de.minecraftadmin.secureban.SecureBan
name: SecureBan
version: ${project.version}
website: http://minecraftadmin.de
description: Let us ban together the whole world
commands:
  localban:
    usage: /<command> [username] [reason]
    description: ban a player localy
    permission: secureban.localban
    permission-message: You dont have permisson to use this command
  globalban:
    usage: /<command> [username] [reason]
    description: ban a player global
    permission: secureban.globalban
    permission-message: You dont have permisson to use this command
  tempban:
    usage: /<command> [username] [numberM/H/D] [reason]
    description: ban a player temporary
    permission: secureban.tempban
    permission-message: You dont have permisson to use this command
  unban:
    usage: /<command> [username]
    description: unban a player
    permission: secureban.unban
    permission-message: You dont have permisson to use this command
  checkban:
    usage: /<command> [username]
    description: list all bans of a player
    permission: secureban.check
    permission-message: You dont have permisson to use this command
  kick:
    usage: /<command> [username] [reason]
    description: kick the player and save it to the database
    permission: secureban.kick
    permission-message: You dont have permisson to use this command
  note:
    usage: /<command> [add|list|remove] [username] [NoteID|NoteMessage]
    description: add/list/remove notes to/from players
permissions:
  secureban.note.*:
    description: permission to all note subcommands
    children:
      secureban.note.add: true
      secureban.note.remove: true
      secureban.note.list: true
  secureban.note.add:
    description: permission to add a new note to a player
    default: op
  secureban.note.remove:
    description: permission to remove a note from a player
    default: op
  secureban.note.list:
    description: permission to list all note to a player
    default: op
  secureban.silent:
    description: permission to join without ban notification
    default: op
  secureban.notify:
    description: permissoin to  see the ban notification message
    default: op
# maintainer
author: BADMAN152
# contributor list
authors: [sourcemaker]
database: true